def coordinator():
    coordinates = {
        'swipe_up':{
            'lower_x1':300,
            'higher_x1':800,
            'lower_y1':1600,
            'higher_y1':1000,
            'lower_trajectory':500,
            'higher_trajectory':700,
            'lower_theta':250,
            'higher_theta':280,
            'lower_duration':200,
            'higher_duration':500},
        'swipe_down':{
            'lower_x1':300,
            'higher_x1':800,
            'lower_y1':500,
            'higher_y1':1000,
            'lower_trajectory':500,
            'higher_trajectory':700,
            'lower_theta':80,
            'higher_theta':120,
            'lower_duration':200,
            'higher_duration':500},
        'like':{
            'min_x':300,
            'max_x':800,
            'min_y':500,
            'max_y':1600,
            'x_displacement':50,
            'y_displacement':50},
        'comment':{
            'x':970,
            'y':1465
        },
        'click_comment_tab':{
            'x':380,
            'y':2220
        },
        'favourite':{
            'min_x':960,
            'max_x':1020,
            'min_y':1600,
            'max_y':1675
        },
        'click_share':{
            'min_x':950,
            'max_x':1030,
            'min_y':1780,
            'max_y':1850
        },
        'download':{
            'min_x':440,
            'max_x':570,
            'min_y':2010,
            'max_y':2140
        },
        'click_home':{
            'min_x':95,
            'max_x':120,
            'min_y':2200,
            'max_y':2215
        },
        'click_info':{
            'min_x':930,
            'max_x':1050,
            'min_y':1060,
            'max_y':1010
        },
        'follow':{
            'min_x':300,
            'max_x':500,
            'min_y':920,
            'max_y':960
        },
        'follow_userpage':{
            'x':400,
            'y':960
        },
        'click_search':{
            'min_x':980,
            'max_x':1010,
            'min_y':190,
            'max_y':235
        },
        'click_confirm_search':{
            'min_x':920,
            'max_x':1000,
            'min_y':190,
            'max_y':210
        },
        'click_search_box':{
            'x':750,
            'y':200,
        },
        'search_clear':{
            'x':800,
            'y':200,
        },
        'click_search_user':{
            'x':600,
            'y':500,
        },
        'click_usertab':{
            'x':500,
            'y':350,
        },
        'click_usertab_firstuser':{
            'x':550,
            'y':550,
        },
        'click_userpage_firstvideo':{
            'x':200,
            'y':1800,
        },
        'click_message':{
            'x':420,
            'y':940,
        },
        'click_comment_send':{
            'x':975,
            'y':1295,
        },
        'click_message_textbox':{
            'x1':400,
            'y1':2200
        },
        'click_message_send':{
            'min_x':965,
            'max_x':1010,
            'min_y':1385,
            'max_y':1430
        },
        'unfollow':{
            'min_x':690,
            'max_x':770,
            'min_y':900,
            'max_y':980
        },
        'back':{
            'min_x':70,
            'max_x':95,
            'min_y':190,
            'max_y':210
        }
    }
    return coordinates